osx_instance:
  image: catalina-xcode

#build_task:
#  name: 'XCode Build Sdk'
#  script: xcodebuild build -workspace SpreedlySdk.xcworkspace -scheme Sdk -destination 'name=iPhone 11'
#
#
#build_sample_task:
#  name: 'XCode Build Sdk Sample'
#  script: xcodebuild build -workspace SpreedlySdk.xcworkspace -scheme Sample -destination 'name=iPhone 11'

test_task:
  name: 'XCode Test'
  install_slather_script: gem install slather
  script:
    - gem install slather
    - xcodebuild test -workspace SpreedlySdk.xcworkspace -scheme SdkTests -destination 'name=iPhone 11' -enableCodeCoverage YES
    - slather coverage --html --scheme Sdk --workspace SpreedlySdk.xcworkspace SpreedlySdk.xcodeproj



#
#test_integration_task:
#  name: 'XCode Integration Test'
#  env:
#    ENV_KEY: ENCRYPTED[!1287e386a4c4842e6d5c0bc59e287437269cca360e77afb04d6a1137f558eff7bf8106c199d6cdcc3dd06355a975e18b!]
#    ENV_SECRET: ENCRYPTED[!be1cd58ee5a27a14be3b9d035cecde24c3081af48fe207ce42e947a9cd6bbc55d857f8855c8b83920b4aba7a53fd65cf!]
#  script:
#    - echo "let secretEnvKey = \"$ENV_KEY\"" > SdkIntegrationTests/Secrets.swift
#    - echo "let secretEnvSecret = \"$ENV_SECRET\"" >> SdkIntegrationTests/Secrets.swift
#    - xcodebuild test -workspace SpreedlySdk.xcworkspace -scheme SdkIntegrationTests -destination 'name=iPhone 11' -enableCodeCoverage YES
#
#lint_task:
#  name: 'Swift Lint'
#  script:
#    - cd Sdk
#    - ../Pods/SwiftLint/swiftlint
